### PR TITLE
Bug/saved data

### LINKED ISSUE #71: Fix SaveData for NetworkManager
Networks should be remembered and loaded back on level reload

### PR DESCRIPTION
**Pull request by D4nders**
Implements persistence for electrical networks using NeoForge's SavedData system. Network state, including ID and member positions, is now saved to `electrorealism_networks.dat` in the world's data folder.

Added Javadocs to `NetworkManager`, `Network` and `NetworkSavedData`.

Refactors `Network` to include `writeToNbt` and `readFromNbt` methods. Updates `NetworkSavedData` to manage saving/loading lists of `Network` NBT. Modifies `NetworkManager` to interact with `NetworkSavedData`, handle loading, member resolution, and trigger saves via `setDirty`.

fix: Correct network data loading after game restart

Resolves an issue where network member positions were lost after completely restarting the game, despite being present in the saved file.

The root cause was identified as `NbtUtils.writeBlockPos` serializing `BlockPos` as `TAG_Int_Array` (ID 11), while the initial loading code expected `TAG_Compound` (ID 10).

The `Network.readFromNbt` method has been updated to correctly detect and parse `TAG_Int_Array` elements within the member position list, ensuring data loads correctly after restarts. Also corrected previous minor NBT key inconsistencies during debugging.

### CODE REVIEW

File: src/main/java/com/teamofelectrorealism/electrorealism/network/NetworkSavedData.java [hunk 1]
```diff
@@ -1,67 +1,173 @@
...
+     * Loads {@link NetworkSavedData} from NBT data. This method is called by the {@link SavedData.Factory}
+     * when loading data from disk. It reads the list of networks from the NBT tag and reconstructs
+     * the {@link NetworkSavedData} instance.
+     *
+     * @param tag      The {@link CompoundTag} containing the saved data.
+     * @param provider The {@link HolderLookup.Provider} for resource lookups.
+     * @return A {@link NetworkSavedData} instance loaded from the NBT data.
+     * @Logs: Exception If there is an error loading a network from the NBT data.
+     */
+    private static NetworkSavedData LoadFromNbt(CompoundTag tag, HolderLookup.Provider provider) {
```
Comment (VetleHJ) [inline src/main/java/com/teamofelectrorealism/electrorealism/network/NetworkSavedData.java]: Change to loadFromNbt() to keep consistent.

**Review by VetleHJ — APPROVED** [review]
